### ISSUE TITLE
GQL- Dependabot cannot update css-what to a non-vulnerable version

### ISSUE THREAD

**Issue by joelpalmer** [Ignigena/micro-now#6]
https://github.com/maxsystems/graphql/security/dependabot/package-lock.json/css-what/open

**Comment by Ignigena** [comment]
This issue should be resolved -- `css-what` was a transitive dependency of `micro-dev`

Long term I think `micro-dev` will probably removed entirely in favor of just using `micro` out of the box. Only really using it in two places and the project hasn't been updated in quite some time.
